### ISSUE TITLE
attempted to start a goroutine without a scheduler

### ISSUE THREAD

**Issue by fernandormoraes** [loopholelabs/scale#91]
When trying to build a Scale Go code with goroutine in Windows (Basically changing function provided in *Get Started*), build fails with message:

`Error: failed to build scale function: unable to compile scale function: scale\scale.go:12:2: attempted to start a goroutine without a scheduler
`

Trying to use cmd.Run() provides the same error with more logs:

```
Error: failed to build scale function: unable to compile scale function: C:\Users\Fernando-PC\scoop\apps\tinygo\current\src\os\exec\exec.go:743:3: attempted to start a goroutine without a scheduler
C:\Users\Fernando-PC\scoop\apps\tinygo\current\src\os\exec\exec.go:716:4: attempted to start a goroutine without a scheduler

```

Reproducible code below:

First example:

```
func Scale(ctx *signature.Context) (*signature.Context, error) {
	go func() {
		fmt.Print("test")
	}()

	ctx.Response().SetBody("Hello, World!")
	return ctx.Next()
}
```

Second example:

```
func Scale(ctx *signature.Context) (*signature.Context, error) {
	cmd := exec.Command("gulp", "serv.dev")
	if err := cmd.Run(); err != nil {
		log.Fatal(err)
	}

	ctx.Response().SetBody("Hello, World!")
	return ctx.Next()
}
```

I investigate some issues trying to debug and discover what was happening, so if this is not a setup misconfiguration in my envinroment, issue below may help:

https://github.com/tinygo-org/tinygo/issues/1272

If this is a bug, i would love to help in contribute in a PR with some guidance, i tried to fix with no success until this moment.

**Comment by ShivanshVij** [comment]
By default ‘scale build’ attempts to build the function using tinygo and the ‘-scheduler=none’ flag 

@dphilla is there any reason we’re doing this? Can we change this?

**Comment by ShivanshVij** [comment]
This is the offending line: https://github.com/loopholelabs/scale-cli/blob/staging/pkg/build/build.go#L192

**Comment by fernandormoraes** [comment]
Can be an interesting parameter to be passed by argument if would'n break anything, i'll change parameter and try some tests

**Comment by fernandormoraes** [comment]
Yep, tried scheduler=tasks and scheduler=asyncify

Output:

```
Error: failed to build scale function: unable to compile scale function: wasm-ld: error: C:\Users\FERNAN~1\AppData\Local\Temp\tinygo3324879902\main.o: undefined symbol: tinygo_startTask
wasm-ld: error: C:\Users\FERNAN~1\AppData\Local\Temp\tinygo3324879902\main.o: undefined symbol: syscall.Faccessat
failed to run tool: wasm-ld
error: failed to link C:\Users\FERNAN~1\AppData\Local\Temp\tinygo3324879902\main: exit status 1

```

So probably has some reason and will not be simple as passing by parameter

**Comment by dphilla** [comment]
`scheduler=asyncify` would be the one to use. The `wasm-ld` error now is related to the exec command or the fmt.Print(), which rely on syscalls which we don't currently provide access to in the WASI builds.

Some context (cc @ShivanshVij): 

IIRC asyncify support for WASI wasn't quite stable during our early investigations here, but now it does now work for WASI builds using goroutines.

So, if you still were still interested in submitting a PR that changes -scheduler=asyncify to be passed in from the cli like `scale build --scheduler=asyncify`, it would be much appreciated :) I think the default should still be -scheduler=none because asyncify does increase the build size a bit.

In the future we can hopefully rely on the [stack-switching](https://github.com/WebAssembly/stack-switching) proposal, or allowed it to be configurable.

**Comment by fernandormoraes** [comment]
@dphilla Thanks for the answer, iam still interested in submit a PR for that and i'll do it soon, i agree in default being `scheduler=none` since that covers most usecases

**Comment by ShivanshVij** [comment]
Instead of adding a `--scheduler` flag to the `build` command directly, I think it would be better if we added a `--tinygo-args` flag instead that to a list of comma separated flags (ie. `--tinygo-args scheduler=none,no-debug`) that way it won't interfere with the rust build, and we can do `--cargo-args` for the rust build.

**Comment by fernandormoraes** [comment]
@ShivanshVij considering language-agnostic purpuses that makes sense, i haven't checked yet if Scale has a predefined syntax for that type of args, but i would go with the follow argument syntax:

scale build --tinygo-args=--scheduler=none,--xarg=yvalue --cargo-args=--xarg=yvalue

Similar to gradlew CLI

Gradlew CLI example:

`./gradlew bootRun -Pargs=--server.port=8999,--spring.application.instance_id=dhn`

What you guys think?

**Note:** i would keep double-dash for general compiler arg as my example suggests

**Comment by ShivanshVij** [comment]
I don't mind that syntax, and we use https://github.com/spf13/cobra to handle parsing args so if Cobra doesn't give you any trouble setting it up like this (I think there's a `StringSlice` flag type you can use)

**Comment by dphilla** [comment]
@fernandormoraes Thank you for your contribution!
